name: Reusable workflow
on: 
  workflow_call:
    inputs:
      artifact_name: 
        description: The name of the artifact to deploy
        type: string
        default: dist-files
    secrets:
      some-secret:
        required: false


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact_name }}
      - name: Output information 
        run: echo "Deploying & uploading ..."